### ISSUE TITLE
ghcup list - show available ghc versions?

### ISSUE THREAD

**Issue by shapr** [haskell/ghcup#10]
I teach Haskell to newbies, they won't know what version to put into `ghcup install <VERSION>` could there be a list command?

**Comment by hasufell** [comment]
Interesting suggestion. Would that be a static list or would it involve scraping upstream urls? Static list sounds easy enough and would also indicate "supported" versions.

**Comment by hvr** [comment]
@hasufell if you can think of a general text format that's happens to be easy to parse in bash (probably a tab-separated-values format would be easiest? any other options?) we could host such a meta-file on downloads.haskell.org

**Comment by hasufell** [comment]
@hvr great suggestion. I wonder if it would make sense to even use [signify](https://github.com/aperezdc/signify) to prepare a release folder for GHC versions. See LibreSSL for example: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

And this is the format of the signify file: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/SHA256

Should be pretty easy to handle with `awk`. In addition, you could provide a symlink url, which points to the "best guess" tarball (latest version built on debian for example), so the script can just fetch https://downloads.haskell.org/~ghc/ghc-latest-unknown-linux.tar.xz (which still has a `ghc-<version>` subfolder, so the script can detect what version we actually fetched).

Just throwing out ideas here.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup/issues/21
