### ISSUE TITLE
Swap tarballs caching default to True

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#11]

**Comment by hasufell** [comment]
These could be cached in `~/.config/ghcup`.

**Comment by LucianU** [comment]
Is there any reason why caching isn't the default? I just had to download ghc 3 times, because of some errors during the install process.

**Comment by hasufell** [comment]
It's possible, but since we have no way of deleting old tarballs currently I thought the default better be off. Note that you can easily create an alias, such as `alias ghcup=ghcup -c`.

ghcup is also used by a haskell package currently and I'm not sure how this would affect them. @Franciman

**Comment by Franciman** [comment]
The only information we rely upon is where ghcup places ghc binaries. So no problem with tarball caching, I like the proposal.

**Comment by LucianU** [comment]
Hm, there's something I don't understand. When you say that you have no way of deleting old tarballs, what tarballs are you referring to?

If `ghcup` doesn't delete tarballs, what happens when an error occurs during the install process? I'm asking, because since it has to download `ghc` again, I'm assuming it doesn't have access to what it downloaded during the previous install attempt.

I agree that creating an alias is

**Comment by hasufell** [comment]
> Hm, there's something I don't understand. When you say that you have no way of deleting old tarballs, what tarballs are you referring to?

The tarballs it downloads.

> If `ghcup` doesn't delete tarballs, what happens when an error occurs during the install process? I'm asking, because since it has to download `ghc` again, I'm assuming it doesn't have access to what it downloaded during the previous install attemp

Of course it has access, otherwise it wouldn't be caching.

The thing is just there is no useful way to determine what tarball he user wants to have cached, which one he doesn't need anymore etc.
So there can be only on assumption: cache everything, never delete. So the user has to delete old tarballs he doesn't need anymore himself.

**Comment by hasufell** [comment]
> 
> * Add a message mentioning the `--caching` flag when the user runs `ghcup install`

Not an option imo. I consider this weird and bad usability to print arbitrary options the user might be interested in. This is a cli tool. Users are expected to run `--help`. 

> * Enable caching by default

Yes, this is what I was considering. 

> * If the install process didn't finish successfully, keep the tarball. This relies on the assumption that the user will try again to install the same version and that the tarball didn't cause the install to fail.
> 

I currently don't know how to do that cleanly.

**Comment by hasufell** [comment]
I've swapped caching only for the `bootstrap-haskell` script for now. Regular `ghcup` invocactions will not enable caching. I believe this is a good compromise for now. `bootstrap-haskell` is primarily usability focused, while `ghcup` should have the minimum of assumptions.
