### ISSUE TITLE
Move into `haskell` org on GitHub

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/ghcup#14]
Hello! Would you be willing to move this script under the "haskell" org? Gershom on reddit says:

> If the ghcup maintainers want to move it there and give it some broader implicit mandate of "community support" I'd be all for it -- it seems like it's been getting quite a bit of uptake lately

https://www.reddit.com/r/haskell/comments/9o75lb/announce_ghc_844_released/e7tm54i/

Thanks :)

**Comment by mitchellwrosen** [comment]
Awesome. cc @gbaz

**Comment by hvr** [comment]
migration's complete now
