### ISSUE TITLE
Suggest using distro packages if known upstream ppas/repos exist

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#16]
There are ubuntu and debian ppas maintained by @hvr afaik, which are recent and well maintained, so we could inform users of this possibility.

**Comment by hasufell** [comment]
There is a note in the README now, I think that is enough. No reason to try to be smart in the script about it.

**Comment by fommil** [comment]
I dunno, I was thinking about this again yesterday and it might be good to be a little smarter about it. I was building a docker image on Debian stretch and the binary that ghcup downloaded didn't work.

If the `install` script detected a supported version of ubuntu/debian then maybe it should shortcut? That way `ghcup` can replace the Haskell Platform on all GNU/Linux distributions... which I think is something that Haskell.org would be interested in // what do you think @hvr ?

Of course... the practicalities of actually **detecting** a specific GNU/Linux distribution may be impossible. I know that a lot of distros provide a fake `/etc/debian_version` file.

**Comment by hasufell** [comment]
> Instead of doing the binary download, just dump the relevant info out with `echo` or make the call (which may result in the user being asked to approved `sudo` commands). Shortcut == completely different code path.

I don't like to make decisions for users. And doing anything remotely sudo-like is a total no-go as well :)

**Comment by fommil** [comment]
I can agree with that. Perhaps the `echo` would be useful though.

**Comment by hasufell** [comment]
> I can agree with that. Perhaps the `echo` would be useful though.

I see a few problems with that:

1. when should the message be echoed? ghcup is mostly non-interactive (and it should), so when a user runs `ghcup install` we echo and install regardless? Or... we require user-interaction and disrupt the non-interactive experience? Or we show it as a message at the end "btw, you could have installed this in a another way"?
2. how often should the message be shown? Every time? Will the user have to silence it? Will we check whether we have already shown it?
3. why can't the user just read the README? ;) ghcup is not there to solve all your problems, it has a specific scope
