### ISSUE TITLE
Get rid of realpath

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#31]
realpath was introduced in coreutils 8.15 [it seems](https://unix.stackexchange.com/a/136527) and is not as portable as we want. E.g., this causes failure on Centos 6.7.

**Comment by hasufell** [comment]
https://gist.github.com/geoff-codes/1f23957288d371b75a2e maybe

**Comment by rpellerin** [comment]
This should be re-opened. On Ubuntu 18.04, ghcup asks for ` realpath` but this package is not available in the Ubuntu repositories.

**Comment by hasufell** [comment]
ghcup doesn't use realpath anymore, since a long time

**Comment by rpellerin** [comment]
When I ran `cabal new-install cabal-install` I got a compile error because `realpath` was missing.

**Comment by hasufell** [comment]
That is cabal, not ghcup. I guess that means you need realpath anyway and we could just require it as well.

**Comment by rpellerin** [comment]
OK thanks. FYI installing `coreutils` apparently adds `realpath`. No more compile error after installing it.
