### ISSUE TITLE
Add get-ghcup installation script

### ISSUE THREAD

**Issue by m-renaud** [haskell/ghcup#36]
The current process to install ghcup, ghc, and cabal requires several steps that could be automated. Other installers (such as [rustup](https://rustup.rs/)) have a very simple process of: `curl https://sh.rustup.rs -sSf | sh` which installs the `rustup` tool, `cargo` (package manager), and `rustc` (the compiler) all in one go. It would be really nice if we could do the same thing with ghcup :)

# Overview

I imagine the end-to-end user journey for someone that's never used Haskell before should be as simple as:

```bash
$ curl https://get.ghcup.haskell.org -sSf | sh
$ source $HOME/.ghcup/env
$ echo 'source $HOME/.ghcup/env' >> $HOME/.bashrc
$ mkdir myproject && cd myproject
$ cabal init -n --is-executable
$ cabal v2-run
```

# Details

To break things down a bit:

`curl https://get.ghcup.haskell.org -sSf | sh`

* Downloads and installs the most recent version of ghcup, ghc, and cabal
    * Separating out the ghc install and cabal install into follow-up work as described in the README seem like unnecessary steps to me, the first thing folks are going to do when they download it is run these commands. 
* If ghcup already exists it should detect this and offer to run `ghcup upgrade`
* Provide instructions for how to add the necessary bin directories to your path: `echo 'source $HOME/.ghcup/env' >> $HOME/.bashrc`

`source $HOME/.ghcup/env`

* The installation script above should create this env file containing: `export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"`

`echo 'source $HOME/.ghcup/env' >> $HOME/.bashrc`

* Make sure $PATH is set properly for future sessions
* This (and the line above) should be copy and paste from the output of the install script

# Implementation

I have a shell script that a wrote that accomplishes most of this now, it needs some polish but if you think this is a good idea I can send a PR and we can discuss more there.

**Comment by gbaz** [comment]
One concern -- I'd rather not tell  people to pipe curl to sh. Instead they should download the script, then run it. I know that many people think it's just fine, but nonetheless there certainly is _some_ understandable concern here and I'd rather just recommend a better practice (see, e.g. https://stackoverflow.com/questions/29382739/why-using-curl-sudo-sh-is-not-advised for more discussion)

**Comment by hasufell** [comment]
We are not suggesting the use of sudo anywhere. ghcup doesn't require sudo and never will.

**Comment by gbaz** [comment]
I appreciate that, but even without sudo quite a lot of damage can be done. C.f. the blogpost linked from that discussion, which isn't about sudo per se: http://blog.emillon.org/posts/2014-12-27-on-the-curl-sh-pattern.html

**Comment by hasufell** [comment]
I can't see strong arguments against this practice on the given link for valid HTTPS sides despite the well known mistrust of https, in which case you shouldn't even trust the GHC binaries that are downloaded (or anything else ghcup downloads like .available-versions and .download-urls).

**Comment by hasufell** [comment]
Reiterating all the hate against `curl | sh` pattern I see very few good arguments.

1. **HTTPS is bad:** applies to everything, including the ghc bindist tarballs, so no argument
2. **executing random content from the internet:** not specific to the piping pattern, people doing the current command from the README are prone to that anyway, unless they read the whole script (which probably most contributors haven't)
3. **piping to sudo:** we don't do that. ever.
4. [curl | sh can be detected server-side to inject malicious content](https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/): very contrived imo. Why not just inject malicious content always? Hit more users.
5. **undefined behavior on incomplete script:** [this](https://www.seancassidy.me/dont-pipe-to-your-shell.html) indicates it might be an actual problem, but I was never able to reproduce this with curl. This seems like the only interesting argument though, but it is extremely easy to fix: we just wrap the entire `bootstrap-haskell` script in a subshell. Incomplete input will then always cause a syntax error.

**Comment by hvr** [comment]
> HTTPS is bad: applies to everything, including the ghc bindist tarballs, so no argument

Generally we consider HTTPS mostly an obfuscation layer; that's why have all those `.sig` files, e.g. http://downloads.haskell.org/ghc/8.6.3/ghc-8.6.3-src.tar.xz.sig ;-)

**Comment by hasufell** [comment]
We don't use signatures currently anyway. I don't see a sensible way to automate that. It would be after all optional and the initial ghcup script download would be completely manual, including verification.

And in the end, people would likely just blindly download some gpg keys and add them to their trust chain. That's similarly secure as HTTPS.

Even the most popular distro don't do that properly. So do we have higher standards?

**Comment by fommil** [comment]
I'd definitely like the option to verify source downloads by SHA256. e.g. if I could provide it as an optional flag, then it's on me to provide the checksum. Doing this for binaries is trickier... but since I don't use the binary downloader I don't have a strong opinion.

**Comment by gbaz** [comment]
Confused by something with https://raw.githubusercontent.com/haskell/ghcup/master/bootstrap-haskell

Why does it run a further  `cabal new-install --symlink-bindir="$HOME/.cabal/bin" --jobs=1 cabal-install` after fetching the cabal binary directly?

**Comment by hasufell** [comment]
> Why does it run a further `cabal new-install --symlink-bindir="$HOME/.cabal/bin" --jobs=1 cabal-install` after fetching the cabal binary directly?

Indeed, but it's also kind of a proof that cabal works right? And the prebuilt cabal tarballs sometimes lack a little bit behind the hackage releases...
