### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#4]

**Comment by gwils** [comment]
I'm interested in having a crack at this.

**Comment by gwils** [comment]
There don't seem to be FreeBSD builds up for GHC 8.6.2 or any modern cabal-install versions, so I'm going to have to tackle that before I can do this. I don't know when I'll have time to do so.

**Comment by hasufell** [comment]
Note that it actually doesn't matter where these things are uploaded, since we are free to use any url, as long as it was built the same way as upstream builds GHC.

**Comment by gwils** [comment]
That's a good point I hadn't considered, but if I have to build these things and upload them somewhere anyway, it may as well be downloads.haskell.org

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup/pull/70

**Comment by hasufell** [comment]
Preliminary support was added in #70
