### ISSUE TITLE
Darwin 8.6.2 installation problem

### ISSUE THREAD

**Issue by jtdaugherty** [haskell/ghcup#48]
I attempted to use `ghcup` to install GHC 8.6.2 on OS X (High Sierra, 10.13.6). After `ghcup` fetched the GHC package and began installation, I ultimately saw a great many lines like
```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/.../.ghcup/ghc/8.6.2/lib/ghc-8.6.2/rts/libHSrts_thr_p.a(elf_reloc_aarch64.thr_p_o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/.../.ghcup/ghc/8.6.2/lib/ghc-8.6.2/rts/libHSrts_thr_p.a(elf_util.thr_p_o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/.../.ghcup/ghc/8.6.2/lib/ghc-8.6.2/rts/libHSrts_thr_p.a(Select.thr_p_o) has no symbols
```
and then the installation terminated with
```
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install "strip" '' '/Users/.../.ghcup/ghc/8.6.2' '/Users/.../.ghcup/ghc/8.6.2/lib/ghc-8.6.2' '/Users/.../.ghcup/ghc/8.6.2/share/doc/ghc-8.6.2/html/libraries' 'v p dyn'
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /private/var/folders/lm/ybj5rc1d5mq7523vdb2fry240000gn/T/tmp.M17dAytH/ghc-8.6.2/libraries/base/dist-install/build/libHSbase-4.12.0.0-ghc8.6.2.dylib
  Reason: image not found
make[1]: *** [install_packages] Abort trap: 6
make: *** [install] Error 2
Failed to install, consider updating this script via: ghcup upgrade
```

**Comment by hasufell** [comment]
Can you show the output of `ghcup debug-info`? Additionally, a complete log via `ghcup --verbose install 8.6.2` would be helpful.

**Comment by jtdaugherty** [comment]
@phadej Yikes! I had no idea that was a GHC issue, but that makes sense. As a I test I tried `ghcup install` which *did* successfully install a working `ghc == 8.4.4` on my Darwin system. So I'll close this since it's not a `ghcup` issue. Thanks!

**Comment by jtdaugherty** [comment]
By the way, I wanted to say: thank you so much for writing this tool! I love it!

**Comment by hasufell** [comment]
Is this requirement documented somewhere? I think the next user might have the same problem. These issues should be documented e.g. here https://www.haskell.org/ghc/download_ghc_8_6_2.html#binaries and our documentation/error messages should point users directly to it. Otherwise this is a usability issue.

**Comment by jtdaugherty** [comment]
@hasufell AFAICT the issue is a bug in the GHC build process that is slated to be fixed in a future release, maybe 8.6.3.

**Comment by berdario** [comment]
[GHC 8.6.3 is out](https://www.haskell.org/ghc/download_ghc_8_6_3.html#macosx_x86_64) with the fix

**Comment by jtdaugherty** [comment]
Great! That makes me wonder if `ghcup` could blacklist `8.6.2` on Darwin to help people avoid the issue. :) Thanks for the update.

**Comment by hasufell** [comment]
We already have a tag `bad` for ghc versions: https://github.com/haskell/ghcup/blob/master/.available-versions#L8

But I haven't really decided on how to use it yet. Because ghcup should be non-interactive... how would you tell the user he's installing a bad version? Basically, he can or should run `ghcup list` first, no?

**Comment by jtdaugherty** [comment]
> how would you tell the user he's installing a bad version?

One possibility is to make `ghcup` require an extra argument like `--force` when installing something tagged with `bad`. If that argument is missing, bail and report an error that the `bad` thing cannot be installed unless the user is totally sure (via `--force`).
