### ISSUE TITLE
How to document bindist requirements

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#49]
Imo, these should be documented upstream and we should point users there (in README and in case of failure): https://www.haskell.org/ghc/download_ghc_8_6_2.html#binaries

Related:

* https://github.com/haskell/ghcup/issues/34
* https://github.com/haskell/ghcup/issues/46
* https://github.com/haskell/ghcup/issues/48

**Comment by hasufell** [comment]
@hvr any progress here? Have you set something up?

**Comment by hasufell** [comment]
ghc is now at gitlab: https://gitlab.haskell.org/ghc/ghc/wikis/index

So we could document there.

**Comment by phadej** [comment]
I still think that `ghcup` should check for easy to check things, e.g. today on `#haskell`

```
11:54  Peppep So now it installed ghc, but when trying to run ghci I get "can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)"
11:58  merijn Peppep: How did you install it and which distro is this?
11:58  Peppep merijn: ghcup on Ubuntu 19.04 beta
```

I cannot recommend `ghcup` to the new people, if they need to read documentation to make complete installation.

**Comment by hasufell** [comment]
> should check for easy to check things

How is that easy to check? You would have to replicate what e.g. autotools do... actually compile a minimal C program to test linking.

**Comment by phadej** [comment]
```
 % dpkg -s libgmp-dev
Package: libgmp-dev
Status: install ok installed
...
```

**Comment by hasufell** [comment]
> On Debian derivatives

And on every other? What do you do on gentoo, exherbo, slackware, FreeBSD, ...
What about different ubuntu versions? Packages may have different names.

Invoking package manager functionality is a non-goal in my opinion.

**Comment by hasufell** [comment]
Invoking package manager to me is still a no go in my opinion:
1. package managers are at the core of a users system, they may have triggers (e.g. mine does, I would not want any application to invoke it, ever)
2. invoking a PM may depend on the distro version, configuration and even require sudo rights. It is unreliable and dangerous. And sudo is not an option.

---

However, I thought about it and this is what we could do:

1. have a `ghcup print-system-requirements` (or similarly named) command (optional, will not be run automatically ever)
2. have haskell-bootstrap invoke this command and require further user confirmation before proceeding

---

`ghcup print-system-requirements` would work this way:

1. figure out the distro
2. download a file from this git repository corresponding to the current distro, e.g. `.requirements/ubuntu`
3. print the contents of the file

If the distro is unknown it will print a default requirements file with the upstream package names instead of distro specific package names.

Caveats:

* it will only care about the `recommended` GHC version and print whatever this one needs
* it will only care about the "latest" or "most common" distro version, there will not be a per-GHC-per-distrover mapping
* as such the information will never be 100% accurate and ghcup will not rely on this subcommand to function

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup/pull/84
