### ISSUE TITLE
MacOS fails to install

### ISSUE THREAD

**Issue by mouse07410** [haskell/ghcup#66]
**Describe the bug**
`bootstrap-haskell` fails on MacOS Mojave 10.14.3 (Macports present). 

Here's the complete log: 
[ghcup-failed.txt](https://github.com/haskell/ghcup/files/2826268/ghcup-failed.txt)
It appears to be failing on 
```
cabal new-install --symlink-bindir=/Users/ur20980/.cabal/bin --jobs=1 cabal-install
```

Here's "condensed" log: 
[new-update2.log.txt](https://github.com/haskell/ghcup/files/2826280/new-update2.log.txt)

It shows the actual error - failure to compile `Network/TCP.hs` because
```
Network/TCP.hs:41:6: error:
    Module ‘Network.Socket’ does not export ‘sClose’
   |
41 |    , sClose, setSocketOption, getPeerName
   |      ^^^^^^
```

**To Reproduce**
1. Clear the previous (the "real") Haskell Platform installation by removing everything Haskell-related.
2. Clone this repo.
3. Set PATH to `$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH`
3. `cd ghcup; ./bootstrap-haskell`
4. Observe the result.

**System information**

```
$ ghcup debug-info
Script version: 0.0.6

Script variables:
  GHC install location:     /Users/ur20980/.ghcup/ghc
  Binary install location:  /Users/ur20980/.ghcup/bin
  Tarball cache location:   /Users/ur20980/.ghcup/cache
  Downloader:               curl --fail -O <url>
  Script update url:        https://raw.githubusercontent.com/haskell/ghcup/master/ghcup
  GHC download baseurl:     https://downloads.haskell.org/~ghc
  Meta download url         https://raw.githubusercontent.com/haskell/ghcup/master/.download-urls
  Meta download format      1
  Meta version url          https://raw.githubusercontent.com/haskell/ghcup/master/.available-versions
  Meta version format       1

Detected system information:
  Architecture:   x86_64
  Distribution:   Darwin
  Distro alias:   darwin
  Distro version: 18.2.0
$ 
```

**Comment by hasufell** [comment]
Have you set `allow-newer` globally or something? You are building a package configuration that is known to not work:

```
 - network-3.0.0.1 (lib:network) (requires download & build)
 - HTTP-4000.3.12 (lib) (requires download & build)
```
https://hackage.haskell.org/package/HTTP-4000.3.12/HTTP.cabal

network-3.0.0.1 does not build with HTTP-4000.3.12 and the cabal file reflects that.

**Comment by hasufell** [comment]
I don't know. Maybe you modified `GHC_PACKAGE_PATH` or something.
