### ISSUE TITLE
Properly check for required commands

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup#8]
E.g. `realpath` was missing in travis, which resulted in funny behavior of `ghcup show`.

**Comment by hvr** [comment]
not sure if this belongs to this issue, but I also noticed that ghcup doesn't check for basic things such as e.g. `make` or a C compiler being in $PATH; thus letting ghcup do a costly tarball download, unpack the dist,  only to fail during the `make install` step of the GHC bindist;

I think it'd provide a better UX if ghcup would fail early on if such basic tools (`make`, `cc`) are missing which commonly *are* missing if you invoke it on a freshly installed Linux distro which hasn't yet had any devel tools installed.

**Comment by hasufell** [comment]
I didn't do that because we have basically no control over the GHC configure script. It can be arbitrarily complex and even change between versions. That leaves us only with the most basic assumptions like checking for make or gcc, which might already be wrong (what about clang, prefixed toolchain etc... the configure script seems to account for a lot of things we cannot really do in our shell script).
