### ISSUE TITLE
ghcup 8.6.4 base library compiled without -haddock support

### ISSUE THREAD

**Issue by coot** [haskell/ghcup#87]
**Describe the bug**
After installing `ghc-8.6.4` with `ghcup`, `ghci` experimental `:doc` command does not show documentation of functions from base.

I noted that `~/.ghcup/ghc/8.6.4/share/doc/ghc-8.6.4/html` seems to be ok.

**To Reproduce**
1. `ghcup install 8.6.4`
2. Run `ghci` and try `:doc print`; I can see the `... Try re-compiling with '-haddock'` message instead of haddock documentation of `print` function.

It works with `ghc-8.6.3` installed with `ghcup`.

**System information**
Paste the output of `ghcup debug-info` and provide additional OS information, if missing.
```
ghcup debug-info
Script version: 0.0.7

Script variables:
  GHC install location:     /home/marcin/.ghcup/ghc
  Binary install location:  /home/marcin/.ghcup/bin
  Tarball cache location:   /home/marcin/.ghcup/cache
  Downloader:               curl --fail -O <url>
  Script update url:        https://raw.githubusercontent.com/haskell/ghcup/master/ghcup
  GHC download baseurl:     https://downloads.haskell.org/~ghc
  Meta download url         https://raw.githubusercontent.com/haskell/ghcup/master/.download-urls
  Meta download format      1
  Meta version url          https://raw.githubusercontent.com/haskell/ghcup/master/.available-versions
  Meta version format       1

Detected system information:
  Architecture:   x86_64
  Distribution:   Gentoo
  Distro alias:   unknown
  Distro version: 
```

**Comment by hasufell** [comment]
This should probably be reported upstream: https://gitlab.haskell.org/ghc/ghc/issues/

**Comment by coot** [comment]
Closing as there is an open [ticket](https://gitlab.haskell.org/ghc/ghc/issues/16415) for it upstream.
