### ISSUE TITLE
ghcup install - just grab the latest stable?

### ISSUE THREAD

**Issue by shapr** [haskell/ghcup#9]
my first try was `ghcup install` would it be possible/sensible for that to just grab the latest? or would that special case be inconsistent?

**Comment by hasufell** [comment]
What is the latest? Afaik there is no unversioned tarball, so we either have a static list of known GHC versions or have to be very smart to figure out what is the latest release.

**Comment by hvr** [comment]
This is related to #10, isn't it?

**Comment by hasufell** [comment]
related to https://github.com/haskell/ghcup/issues/21
