### ISSUE TITLE
Dependency to Homebrew on macOS

### ISSUE THREAD

**Issue by m-schmidt** [haskell/ghcup#97]
Is the dependency of `ghcup` to the external utility `xz` intended? `xz` is not installed by default on macOS. Installing Haskell Platform therefore requires the installation of things like Homebrew etc just to get a compression utility:

    To install and run GHC you need the following dependencies:
    Following commands are required, but missing, please install:  xz

Wouldn't it be better to use `gzip`?

**Comment by hasufell** [comment]
How would you unpack official ghc bindists with gzip?
https://downloads.haskell.org/~ghc/8.6.5/
https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-apple-darwin.tar.xz

**Comment by m-schmidt** [comment]
Bummer. We can close this here.

**Comment by llelf** [comment]
> How would you unpack official ghc bindists with gzip?

By doing `gunzip`.
Also macOS’ tar is `bsdtar` and unpacks xz fine too.

**Comment by hasufell** [comment]
@llelf If you want to implement that, check https://github.com/haskell/ghcup/blob/master/ghcup#L1015-L1046

Since I don't run macOS and try to keep close to POSIX, I didn't do any platform specific logic.
