### ISSUE TITLE
Installation failure failure - Darwin Mojave 10.14.4

### ISSUE THREAD

**Issue by justanotherdot** [haskell/ghcup#98]
**Describe the bug**
Tried running the provided installation script on the README:

`$ curl https://raw.githubusercontent.com/haskell/ghcup/master/bootstrap-haskell -sSf | sh`

resulting in an installation failure. I tried the recommended `ghcup upgrade` to no avail. Rerunning the install command directly with verbose gives us:

```
$ ~/.ghcup/bin/ghcup --cache --verbose install
mkdir -p /Users/$USER/.ghcup
mkdir -p /Users/$USER/.ghcup/bin
mkdir -p /Users/$USER.ghcup/cache
rm /Users/$USER/.ghcup/cache/.available-versions
rm /Users/$USER/.ghcup/cache/.download-urls
cd /Users/$USER/.ghcup/cache
curl --fail -O https://raw.githubusercontent.com/haskell/ghcup/master//.available-versions
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   686  100   686    0     0  10630      0 --:--:-- --:--:-- --:--:-- 10718
cd /Users/$USER/.ghcup/cache
curl --fail -O https://raw.githubusercontent.com/haskell/ghcup/master//.download-urls
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9237  100  9237    0     0   165k      0 --:--:-- --:--:-- --:--:--  167k
Installing GHC-8.6.3 for Darwin on architecture x86_64
cd /var/folders/dx/v1bjflqj2q741k8fy6hpwglm0000gn/T/tmp.TWp3Ad3g
xz -cd "/Users/$USER/.ghcup/cache/ghc-8.6.3-x86_64-apple-darwin.tar.xz" | tar -xf -
cd ghc-8.6.3
/Users/$USER/.ghcup/bin/ghcup: line 498: cd: ghc-8.6.3: No such file or directory
Failed to install, consider updating this script via: ghcup upgrade
```

I think the tarball extraction failed, as there is no directory under temporary directory:

```
$ ls -a /var/folders/dx/v1bjflqj2q741k8fy6hpwglm0000gn/T/tmp.TWp3Ad3g
./      ../
```

However, when I run the same command manually, the directory shows up:

```
$ cd /var/folders/dx/v1bjflqj2q741k8fy6hpwglm0000gn/T/tmp.KnXd9jmC
$ xz -cd ~/.ghcup/cache/ghc-8.6.3-x86_64-apple-darwin.tar.xz | tar -xf -
$ ls
ghc-8.6.3/
```

so it would appear that the tar extraction isn't necessarily failing to produce a directory unless it's something specific to the script. Any ideas?

**To Reproduce**
1. ` curl https://raw.githubusercontent.com/haskell/ghcup/master/bootstrap-haskell -sSf | sh`

**System information**
```
Script version: 0.0.7

Script variables:
  GHC install location:     /Users/$USER/.ghcup/ghc
  Binary install location:  /Users/$USER/.ghcup/bin
  Tarball cache location:   /Users/$USER/.ghcup/cache
  Downloader:               curl --fail -O <url>
  Script update url:        https://raw.githubusercontent.com/haskell/ghcup/master//ghcup
  GHC download baseurl:     https://downloads.haskell.org/~ghc
  Meta download url         https://raw.githubusercontent.com/haskell/ghcup/master//.download-urls
  Meta download format      1
  Meta version url          https://raw.githubusercontent.com/haskell/ghcup/master//.available-versions
  Meta version format       1

Detected system information:
  Architecture:   x86_64
  Distribution:   Darwin
  Distro alias:   darwin
  Distro version: 18.5.0
```

**Comment by hasufell** [comment]
If you look at the source code, the debug line lies a bit:
https://github.com/haskell/ghcup/blob/master/ghcup#L1032

What we do is invoking a subshell:
```
( xz -cd "${filename}" | tar -xf - ; ) || die "unpacking failed!"
```

If anything there fails, then the whole shell invocation should fail. I also noticed that you used `~/.ghcup` instead of `/Users/$USER/.ghcup` in your manual invocation.

I currently don't know what's happening. Don't have an OSX vm to test.

**Comment by justanotherdot** [comment]
Looks like doing the expanded version doesn't make much difference:

```
$pwd
/var/folders/dx/v1bjflqj2q741k8fy6hpwglm0000gn/T/tmp.TWp3Ad3g
$ xz -cd /Users/$USER/.ghcup/cache/ghc-8.6.3-x86_64-apple-darwin.tar.xz | tar -xf -
$ ls
ghc-8.6.3/
```

I'll try to poke around a bit as well and report back with some more info.

**Comment by dwijnand** [comment]
> Don't have an OSX vm to test.

(JFYI Travis CI has support for macOS, but also last time I tried they were slow.)

**Comment by justanotherdot** [comment]
I tried to do a bit of debugging today but couldn’t figure out why the cd
would fail saying the directory is missing when it was definitely still
there when I removed the cleanup steps.

My best current hunch is there may be some weirdness between the temporary
directory and the cache directory but from what I could tell everything was
happening in the temporary directory. One thing I didn’t check was the
permissions on the unpacked directory.

**Comment by justanotherdot** [comment]
I’ll also try on my linux box just to see if it’s something weird I have
setup causing issues.

**Comment by justanotherdot** [comment]
Runs fine on debian buster from my end. I'll check the permissions like I mentioned above and poke a bit more on the OS X specific case when I find some time.

**Comment by justanotherdot** [comment]
Despite the current working directory being the temporary directory that's setup in the prior code (https://github.com/haskell/ghcup/blob/master/ghcup#L1355 and https://github.com/haskell/ghcup/blob/master/ghcup#L1358 so in both branches prior), it having the right permissions, ownership, etc. I only got this to work by having the absolute path provided, e.g. `        edo cd "${tmp_dir}/ghc-${myghcver}"`. 

I have no idea if:

* This is some darwin specific quirk
* A shell specific quirk (I was running in zsh, I can try in bash)
* or if this breaks for any bizarre reason on other platforms

I'm happy to raise a PR for this if you'd like.

**Comment by hasufell** [comment]
Are you *exporting* CDPATH? That's dangerous.

**Comment by hasufell** [comment]
I fixed it slightly differently. Should work now.

**Comment by justanotherdot** [comment]
Yeah I think I’ve done this out of habit to mark some others vars accessible where I need them to be to sub shells. Cheers for the patch up, although it would seem more of a config issue on my end.
